language: node_js
node_js:
- node
jobs:
  include:
  - stage: test
    name: Unit Tests
    script: npm test
  - stage: test
    name: Linting
    script: npm run lint
  - stage: build
    name: Build container
    install: skip
    script: |
      docker image build -t "registry.heroku.com/toy-do/web:${TRAVIS_BUILD_NUMBER}" .
      echo "${HEROKU_API_KEY}" | docker login --username=_ --password-stdin registry.heroku.com
      docker image push "registry.heroku.com/toy-do/web:${TRAVIS_BUILD_NUMBER}"
  - stage: acceptance-tests
    name: Acceptance tests
    install: skip
    script: |
      export WEB_IMAGE="registry.heroku.com/toy-do/web:${TRAVIS_BUILD_NUMBER}"
      echo "${HEROKU_API_KEY}" | docker login --username=_ --password-stdin registry.heroku.com
      docker-compose run tests
  - stage: database
    if: branch = master
    name: Database migration
    script: |
      export NODE_ENV=production
      export $(heroku config:get --app toy-do --shell DATABASE_URL | tr -d \')
      npm run db:migrate
  - stage: deploy
    if: branch = master
    name: Deploy
    install: skip
    script: "./deploy.sh"
  - stage: smoke-test
    if: branch = master
    name: Smoke test
    install: skip
    script: curl --silent --show-error --fail https://toy-do.herokuapp.com
env:
  global:
    secure: caIfHd2xqFiIWQAzQiphREwoKpEqYmWrcYUU2+y5ZYf5o4aiD44ui5ZtCC8R+QAuY+jqtMX9r8xogWqPChGmL5jFRuTF7zjKed/4z9OzezaffZwFlOy3j40oUpVtvosBJ9S6kguSE7pCTlztgwVkswf1Bb/Iqo5vjw5ECk1LzMr8O4ykr1oT+40q9h2Fbf+x/T31mbUToHxG2Y4w/p7pIlR3HWmmSkX9WJwJQkHm/OtjoN0mJDwe0t2wK7HWGzsDZXA1boILjc0s0OQjZvHWA5XkeRwEUzJgLNn38FQL0R946jTSgh/iL+kD+Ew9R76s+bHbf/itEA8exTV1N7X1hHPtnxuMSN+ycOHSMMI1lF5e3TvWygfbLL0S1U3eQq3fV91PUr6p/LlBMTwIvdNmqahuUle5eyxAMwYPHn1eHXQa4QdG22vuQvJ5G7A39fVl7EPe2Bp3d67JygzTPok+vp6TzeXNJYJAhu8RrHyk7MIN8Hj06tbdIXpM1ujIb1nclkHKZgAuQbTq1+ie26yhY026j5pnkrwoVZ6Enb00NoLDbnImHrrxNJ5XRkc+8mp/Hr/nkdyyVpXgkJ9tNCQVnEjHm+dqaWFfUut/4pSWxAhRL01yyWAu89wKszQXT8jyFyhVFLVUI4ltlFgCn176aoBSP7Vw1OHxf32vSf2yb68=
