version: "3.7"
services:
  web:
    image: ${WEB_IMAGE}
    environment:
      NODE_ENV: staging
      DATABASE_URL: postgres://web:pass@db:5432/todo
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: todo
    volumes:
      - type: bind
        source: ./migrations
        target: /docker-entrypoint-initdb.d
  tests:
    image: cypress/included:3.4.1
    environment:
      - CYPRESS_baseUrl=http://web:3000
    working_dir: /e2e
    volumes:
      - type: bind
        source: .
        target: /e2e
    depends_on:
      - web
